#!/usr/bin/env bash

alias bt='bash /home/drube/tls/scripts/bt.sh'
alias bcb='bash /home/drube/tls/scripts/bcbuildScript.sh'
alias tst='bash /home/drube/tls/scripts/testRunScript.sh'
alias br='bash /home/drube/tls/scripts/runBricscad.sh'
alias tapp='bash /home/drube/tls/scripts/launch_bcadtestapp.sh'
alias bcbl='bash /home/drube/tls/scripts/latest_build.sh'
alias nin='bash /home/drube/tls/scripts/ninjaBuildScript.sh'
alias xmlb='bash /home/drube/tls/scripts/buildXmlRes.sh'
alias qmll='bash /home/drube/tls/scripts/qmlLinter.sh'
alias rub='google-chrome-stable --profile-directory="Profile 1"'
alias rob='google-chrome-stable --profile-directory="Default"'
alias boa='google-chrome-stable --profile-directory="Default" https://boa.bricsys.com/boa/timesheets/overview.do'
alias spr='google-chrome-stable --profile-directory="Default" https://redmine.bricsys.com/projects/ai-core/agile/board?query_id=2363'
alias brr='google-chrome-stable --profile-directory="Default" https://github.com/HEXAGON-GEO/bricscad'
alias pro='google-chrome-stable --profile-directory="Default" https://github.com/HEXAGON-GEO/bricscad/pulls/rubenderaeve-hexagon'
alias chat='google-chrome-stable --profile-directory="Default" https://chatgpt.com/'
alias chatt='google-chrome-stable --profile-directory="Default" https://m365.cloud.microsoft/chat/'
alias renameFile='bash /home/drube/tls/scripts/renameFile.sh'
alias wha='google-chrome-stable --profile-directory="Profile 1" https://web.whatsapp.com/'
alias mus='bash /home/drube/tls/scripts/random-music.sh'

